export interface GuideStep { title: string; body: string }
export interface GuideFAQ { q: string; a: string }
export interface Guide {
  slug: string;
  title: string;
  query: string;
  metaDescription: string;
  intro: string;
  steps: GuideStep[];
  tips: string[];
  faq: GuideFAQ[];
  relatedTool: string;
  keywords: string[];
  publishedAt: string;
}

export const guides: Guide[] = [
  {
    slug: 'how-much-life-insurance-do-i-need',
    title: 'How Much Life Insurance Do I Need? (DIME Method + Examples)',
    query: 'how much life insurance do i need',
    metaDescription: 'Calculate how much life insurance you need with the DIME method: Debt + Income + Mortgage + Education. Worked examples for ages 30, 40, and 50.',
    intro: 'Most online quizzes throw out a number like "10× your salary" and call it done. That works for some people and badly underestimates everyone with kids or a mortgage. The DIME method — Debt, Income, Mortgage, Education — gives you a coverage number tied to your actual obligations, not a generic multiplier.',
    steps: [
      { title: 'Add up your non-mortgage debt (D)', body: 'Credit cards, car loans, student loans, personal loans, medical debt. The goal is for your family to clear these without selling assets. If you have $18,000 in cards and a $22,000 car loan, that is $40,000 of D.' },
      { title: 'Multiply your income by years of replacement (I)', body: 'How many years of your salary should the policy replace? Typical answers: until your youngest child turns 18, or until your spouse reaches retirement. A 35-year-old earning $80,000 with a 5-year-old usually picks 13 years × $80,000 = $1.04M for I.' },
      { title: 'Add the mortgage payoff (M)', body: 'The current loan balance, not the original amount and not the home value. If you owe $310,000, M = $310,000. This lets your family stay in the house without scrambling for a refi.' },
      { title: 'Add education costs per child (E)', body: 'In-state public 4-year is roughly $108,000 in 2026 (tuition, fees, room, and board). Private averages closer to $230,000. Pick the school type you actually expect, not the cheapest, and multiply by number of kids.' },
      { title: 'Subtract what you already have', body: 'Existing employer life insurance, savings, taxable investments, and your spouse\'s income capacity. If your DIME total is $1.6M and you have $200,000 saved + $150,000 in employer coverage, you need $1.25M in new coverage.' },
      { title: 'Round up, do not round down', body: 'Coverage is priced in tiers ($500K, $750K, $1M, $1.5M, $2M). Going from $1.25M to $1.5M usually adds $4–$8/month for healthy applicants under 45. The buffer matters more than the savings.' },
      { title: 'Buy term, not whole, unless you have a specific reason', body: 'For 95% of households, a 20- or 30-year level term policy at 10–15× the price you would pay for whole life is the right answer. Use the calculator on this site to see the cost gap over 20 years.' },
    ],
    tips: [
      'If your spouse stays home, do not put their coverage at zero. Replacing childcare, household management, and lost income capacity typically requires $250,000–$500,000.',
      'Buy in your 30s if you can. Premiums roughly double every decade for the same coverage and same health rating.',
      'Get the medical exam version, not no-exam. No-exam policies are 30–80% more expensive for healthy people.',
      'Lock the policy length to your need date — the year your youngest finishes college or your mortgage pays off, whichever is later.',
    ],
    faq: [
      { q: 'Is 10× my salary a good rule of thumb?', a: '10× works as a fast sanity check but consistently underestimates parents and homeowners. A $90,000 earner with two kids and a mortgage usually needs $1.5–$2M, which is closer to 17–22×. Use DIME for the real number.' },
      { q: 'Do stay-at-home parents need life insurance?', a: 'Yes, usually $250,000–$500,000 of term coverage. Replacing childcare alone runs $20,000–$30,000 per year per child in most US metros. Add household management and the loss of future earning capacity and the number rises fast.' },
      { q: 'Should I count my employer-provided life insurance?', a: 'Yes, but discount it. It usually disappears the day you change jobs, and the typical 1× or 2× salary employer policy is well below DIME for anyone with a family. Treat it as a supplement, not a foundation.' },
      { q: 'What term length should I pick — 20 or 30 years?', a: 'Pick the longer of: years until your youngest is 22, or years until your mortgage is paid. A 32-year-old with a 2-year-old and a 30-year mortgage almost always picks 30-year term.' },
      { q: 'Is term life cheaper if I quit smoking?', a: 'Dramatically. Smokers pay 2.5–3.5× the rate of non-smokers for the same coverage. Most carriers reclassify you after 12 months smoke-free. Apply, then re-shop after a year off cigarettes.' },
      { q: 'Can I get life insurance with high blood pressure or diabetes?', a: 'Almost always yes, with controlled conditions. Type 2 diabetes managed with diet or metformin and an A1C under 7 typically rates Standard or Standard Plus. Use a broker who shops 10+ carriers — rates vary 60% across companies for the same applicant.' },
    ],
    relatedTool: 'life-insurance-calculator',
    keywords: ['how much life insurance do i need', 'dime method life insurance', 'life insurance coverage calculator', 'how much life insurance', 'life insurance amount'],
    publishedAt: '2026-05-09',
  },
  {
    slug: 'term-vs-whole-life-insurance',
    title: 'Term vs Whole Life Insurance: Honest Comparison (2026)',
    query: 'term vs whole life insurance',
    metaDescription: 'Term vs whole life: real cost differences, when each makes sense, and the math behind "buy term and invest the difference." Worked examples + decision framework.',
    intro: 'Whole life policies cost 8–15× more per dollar of coverage than term, and that gap funds a cash value account growing at 2–4%. For most households, the math says buy term and put the savings in a Roth IRA. Here is when whole life actually makes sense and how to run the comparison yourself.',
    steps: [
      { title: 'Get a real quote on both', body: 'A healthy 35-year-old non-smoker pays roughly $30/month for $500K of 20-year term, or $385/month for $500K of whole life. Same coverage, 12.8× the cost. Get actual quotes — your numbers, not averages.' },
      { title: 'Calculate the "buy term, invest the difference" math', body: 'Take the monthly difference ($355 in the example above) and assume it goes into a low-cost index fund at a 7% real return for 20 years. That is roughly $185,000 in inflation-adjusted dollars. Whole life cash value over the same period typically lands at $90,000–$120,000.' },
      { title: 'Decide if you actually need permanent coverage', body: 'Term covers 95% of cases — you need protection while kids are home and the mortgage is unpaid. After that, your accumulated assets replace the insurance. Whole life only beats term if you have a specific permanent need: special-needs dependent, estate tax exposure, business buy-sell agreement.' },
      { title: 'Check the surrender table on whole life policies', body: 'Most whole life policies have negative cash value for the first 3–7 years. If you cancel at year 5, you typically get back 30–60% of premiums paid. This is the biggest hidden cost — most people who buy whole life eventually lapse it.' },
      { title: 'Run the breakeven', body: 'For most policies, the cash value does not exceed cumulative premiums paid until year 12–15. If you might need flexibility before then, whole life is a worse savings vehicle than a taxable brokerage.' },
      { title: 'If you still want permanent coverage, look at guaranteed universal life (GUL) instead', body: 'GUL is permanent like whole life but stripped of the savings component, costing 30–50% less. A 40-year-old non-smoker pays roughly $200/month for $500K GUL to age 100, vs $420/month for $500K whole life.' },
    ],
    tips: [
      'Insurance agents earn 90–105% of first-year whole life premium as commission. Term commissions are 30–60%. Be aware of who benefits from which sale.',
      'If you have already had whole life for 10+ years, do not necessarily cancel — the math gets better the longer you hold. Get a current cash surrender value quote and run the numbers.',
      'For estate planning at $13M+ net worth, second-to-die whole life can pay estate taxes efficiently. Below that threshold, the standard estate exemption covers most families.',
    ],
    faq: [
      { q: 'Is whole life ever worth it?', a: 'Yes, for three specific cases: (1) you need permanent coverage for a special-needs dependent, (2) you are using it for estate liquidity over the federal estate exemption, or (3) it is part of an irrevocable life insurance trust. Outside those cases, term plus separate investing wins on the math nearly every time.' },
      { q: 'What happens to my term policy at the end of the term?', a: 'It expires. You can usually renew at much higher rates (3–8× the original premium) or convert a portion to permanent coverage if your policy includes a conversion rider. The point of term is to bridge the years when you need protection — by the time it expires, you should be self-insured through accumulated assets.' },
      { q: 'Can I borrow against whole life cash value?', a: 'Yes, typically at 5–8% interest. The loan reduces your death benefit dollar-for-dollar until repaid, and unpaid loans at death come out of the payout. It is a legitimate liquidity tool but expensive — most home equity lines and 401(k) loans cost less.' },
      { q: 'Will whole life dividends keep up with inflation?', a: 'Usually no. Mutual whole life dividends have averaged 5–6% over the last decade on a participating policy, but that is on the cash value, not the death benefit. Inflation-adjusted real return after fees and cost of insurance is typically 1–3%.' },
      { q: 'Is "infinite banking" with whole life a good idea?', a: 'It is a marketing concept built around using whole life cash value loans as a private financing system. The math only works if you would otherwise borrow at higher rates than the policy loan rate. For homeowners with HELOC access at prime rate, it rarely pencils out.' },
    ],
    relatedTool: 'term-vs-whole-life',
    keywords: ['term vs whole life', 'term vs whole life insurance', 'is whole life insurance worth it', 'buy term invest the difference', 'permanent vs term life'],
    publishedAt: '2026-05-09',
  },
  {
    slug: 'how-much-car-insurance-do-i-need',
    title: 'How Much Car Insurance Do I Need? Coverage Limits Explained',
    query: 'how much car insurance do i need',
    metaDescription: 'State minimums are not enough. How to set liability, comprehensive, collision, and uninsured motorist coverage based on your assets and vehicle.',
    intro: 'Most state minimum liability limits ($25K/$50K/$25K is common) do not cover one trip to the ER for the other driver. Here is how to set each coverage type to actually protect your assets, with real cost-vs-protection numbers.',
    steps: [
      { title: 'Set bodily injury liability to at least 100/300', body: 'That is $100,000 per person, $300,000 per accident. State minimums of $25K/$50K disappear in any serious crash — average ER admission for car-accident injury is $42,000 before surgery. The premium difference between 25/50 and 100/300 is usually $80–$180/year.' },
      { title: 'Set property damage liability to $100,000', body: 'You can total a Tesla Model Y or a luxury SUV in a single fender-bender. State minimums of $25K cover almost nothing on the road in 2026. Going from $25K to $100K adds roughly $40–$70/year.' },
      { title: 'Match uninsured/underinsured motorist (UM/UIM) to your liability', body: '14% of US drivers have no insurance and another 20% are underinsured. UM/UIM covers your medical bills if they hit you. Buy at the same limits as your liability — same logic, your protection should match what you would owe someone else.' },
      { title: 'Pick collision and comprehensive only if your car is worth keeping', body: 'Rough rule: drop both when the annual premium for them exceeds 10% of the car\'s actual cash value. A 2014 Camry worth $9,000 should not have $1,200/year in collision + comp. A 2023 RAV4 worth $32,000 absolutely should.' },
      { title: 'Set deductibles to $1,000 minimum', body: 'Going from $500 to $1,000 typically saves $80–$140/year on collision + comp combined. The breakeven is 4–6 years between claims, which most safe drivers easily exceed. Higher deductibles also discourage filing small claims that raise your rate.' },
      { title: 'Add an umbrella policy if your assets exceed $300K', body: 'A $1M personal umbrella runs $200–$400/year and stacks on top of your auto liability. If you own a home, have retirement accounts, and earn well, you have more assets at risk than 100/300 protects.' },
    ],
    tips: [
      'Re-shop every 2 years. Insurers raise rates on existing customers far more than on new applicants — the average loyal customer overpays by 18–28% according to recent state DOI studies.',
      'Bundle home + auto with the same carrier only if the bundle discount exceeds the premium gap. Run the math; sometimes the cheapest auto carrier and cheapest home carrier separately beat the bundle.',
      'Use telematics if you drive less than 10,000 miles/year. Programs like Progressive Snapshot, State Farm Drive Safe, and Allstate Drivewise typically save 15–30% for low-mileage safe drivers.',
    ],
    faq: [
      { q: 'What is the cheapest car insurance I can legally have?', a: 'Whatever your state minimum is, but "cheapest" and "adequate" are very different. State minimum policies cost $400–$900/year nationally; getting hit with a real claim above your limits exposes your savings, retirement accounts, and future wages to garnishment.' },
      { q: 'Do I need full coverage on a paid-off car?', a: 'Only if losing the car would create real hardship. If you can afford to replace the vehicle out of pocket and the comp + collision premium is more than 10% of the car\'s value annually, drop it.' },
      { q: 'Is the difference between 50/100 and 100/300 worth it?', a: 'Almost always yes. The premium gap is typically $40–$120/year while the protection gap is $50,000 per person and $200,000 per accident. One serious injury claim wipes out a decade of "savings" from running lower limits.' },
      { q: 'What is gap insurance and do I need it?', a: 'Gap insurance covers the difference between your loan balance and the car\'s actual cash value if it is totaled. New cars depreciate 20–30% in year one — if you put less than 20% down or financed for 60+ months, you almost certainly need gap until the loan balance drops below the car\'s value.' },
      { q: 'How much can I save by raising my deductible from $500 to $2,000?', a: 'Typically $180–$320/year combined on collision and comprehensive, depending on vehicle and ZIP code. Worth it if you have $2,000 in liquid savings; not worth it if a $2,000 surprise bill would put you on a credit card.' },
    ],
    relatedTool: 'auto-insurance-calculator',
    keywords: ['how much car insurance do i need', 'car insurance coverage limits', 'auto insurance liability limits', 'car insurance amounts', 'recommended car insurance coverage'],
    publishedAt: '2026-05-09',
  },
  {
    slug: 'average-car-insurance-cost-by-state',
    title: 'Average Car Insurance Cost by State (2026 Rates)',
    query: 'average car insurance cost by state',
    metaDescription: 'State-by-state average car insurance premiums, the factors that drive your rate, and how to tell if you are overpaying.',
    intro: 'The national average for full-coverage car insurance in 2026 sits around $2,150/year, but state averages range from $1,180 (Vermont) to $3,950 (Louisiana). Your actual rate depends more on six personal factors than your state — but state matters for the floor and ceiling.',
    steps: [
      { title: 'Look up your state\'s average', body: 'Cheapest five states (2026): Vermont ($1,180), Idaho ($1,290), New Hampshire ($1,310), Maine ($1,340), Ohio ($1,420). Most expensive five: Louisiana ($3,950), Florida ($3,710), Michigan ($3,580), New York ($3,490), Nevada ($3,180).' },
      { title: 'Compare your premium to the state average', body: 'If you pay within 15% of the average, you are in line. More than 25% above? You have something raising your rate — recent at-fault claim, low credit-based insurance score, high-risk vehicle, or simply a carrier that does not like your profile.' },
      { title: 'Identify the six rate factors that matter most', body: 'In rough order of impact: driving record (worth 40–80% rate increases for a single at-fault), credit-based insurance score (20–80% in states that allow it), age and gender (under-25 males pay 50%+ more), ZIP code (urban dense ZIPs cost 2× rural), vehicle (new luxury = highest), and annual mileage.' },
      { title: 'Pull your CLUE report', body: 'CLUE is the insurance industry\'s claim history database. You get one free copy per year from LexisNexis. If a prior claim is reported wrong or a claim you withdrew is showing, dispute it — that single fix can drop your rate 10–30%.' },
      { title: 'Re-quote with at least 4 carriers', body: 'Rate spreads of 60–120% across carriers for the same driver are normal. The cheapest carrier for a 28-year-old in suburban Phoenix might be the most expensive for a 55-year-old in rural Iowa. Always quote your specific profile, not "best carriers" lists.' },
      { title: 'Apply discounts you actually qualify for', body: 'Common ones: paid-in-full (4–10%), paperless billing (1–3%), telematics (10–30%), good student (8–15%), home/auto bundle (10–22%), defensive driving course (5–10%), low annual mileage under 7,500 (5–15%). Stack them.' },
    ],
    tips: [
      'Florida\'s no-fault PIP system explains most of its high cost. Michigan\'s unlimited PIP medical was the previous cause; reforms have lowered the average but Detroit ZIPs still see $4,500+ averages.',
      'In California, Massachusetts, Hawaii, and Michigan, credit-based scoring is restricted or banned for auto. Moving from a credit-using state to one of these typically helps anyone with a credit score under 700.',
      'Annual mileage is self-reported and rarely audited unless you file a claim. Be honest, but if you genuinely commute less than 7,500 miles/year, document it — this discount alone can save 10–15%.',
    ],
    faq: [
      { q: 'Why is car insurance more expensive in Louisiana and Florida?', a: 'Both states have unusually high lawsuit frequency in auto cases, low judicial caps on non-economic damages, and (in Florida) widespread roof-related litigation that crosses into the auto market through bundled carrier exposure. Louisiana also has a unique direct-action statute that lets injured parties sue insurers directly.' },
      { q: 'Does my credit score really affect my car insurance rate?', a: 'In 47 states, yes — heavily. The "insurance score" is a credit-derived number that statistically correlates with claim frequency. Improving from a 620 to a 720 typically reduces auto premiums 15–35% in scoring states.' },
      { q: 'Is car insurance cheaper if I pay annually instead of monthly?', a: 'Yes, by 4–10% on the total premium plus you avoid monthly installment fees of $4–$8 per cycle. If you can swing the lump sum, do it — that discount is essentially a 4–10% guaranteed annual return on the cash you would have spent monthly.' },
      { q: 'How long do tickets and at-fault accidents stay on my record?', a: 'For insurance rating, most carriers look back 3–5 years. A speeding ticket adds about 15–25% for 3 years; an at-fault accident adds 30–60% for 3–5 years; a DUI adds 70–150% for 5+ years and many carriers will non-renew.' },
      { q: 'Can my insurance cancel me for one accident?', a: 'Mid-policy cancellation requires fraud or non-payment in nearly every state. Non-renewal at the end of the term is permitted, and a serious at-fault accident or pattern of small claims can trigger one. Most cancellations come from the policyholder switching carriers, not the carrier dropping them.' },
    ],
    relatedTool: 'car-insurance-comparison',
    keywords: ['average car insurance cost', 'car insurance cost by state', 'auto insurance rates by state', 'how much is car insurance', 'cheapest car insurance state'],
    publishedAt: '2026-05-09',
  },
  {
    slug: 'how-much-home-insurance-do-i-need',
    title: 'How Much Home Insurance Do I Need? Replacement Cost Guide',
    query: 'how much home insurance do i need',
    metaDescription: 'Set dwelling, personal property, liability, and loss-of-use coverage based on replacement cost — not market value or purchase price.',
    intro: 'Home insurance is sized to rebuild cost, not market value. A house that sells for $620,000 might cost $410,000 to rebuild, or $730,000 — the answer depends on construction type, ZIP code labor costs, and finishes. Most homeowners under-insure by 20–40% because they confuse market value with replacement cost.',
    steps: [
      { title: 'Calculate dwelling coverage at full replacement cost', body: 'Multiply your home\'s square footage by current local rebuild cost. In 2026 that is roughly $180–$240/sqft for tract-grade construction, $240–$360/sqft for mid-grade, and $360–$600+/sqft for custom or coastal. A 2,400 sqft tract home in suburban Atlanta = $475,000–$575,000 dwelling.' },
      { title: 'Add an extended replacement cost endorsement', body: 'Standard policies cap at the dwelling number. Extended replacement adds 25–50% on top, so if rebuild costs spike (post-disaster labor + materials), you are not on the hook. The endorsement costs 2–5% of the base premium and is essentially mandatory in fire-prone or hurricane-prone areas.' },
      { title: 'Set personal property at 50–75% of dwelling', body: 'Default policies often set this automatically at 50%. If you have above-average belongings — bicycles, electronics, jewelry, art, instruments, professional equipment — push it to 70–75%. Jewelry, firearms, and collectibles need separate scheduled riders above $1,500–$2,500 sub-limits.' },
      { title: 'Choose actual cash value vs replacement cost', body: 'Replacement cost pays to replace stolen or damaged items new. Actual cash value pays depreciated value. Always pick replacement cost on personal property — the premium difference is small, the claims difference is large.' },
      { title: 'Set liability to $300K minimum, $500K if you have assets', body: 'Standard $100K liability is inadequate. Lawsuits over dog bites and slip-and-falls regularly settle for $50K–$250K. The premium gap from $100K to $500K is typically $40–$90/year. Add a $1M umbrella above that for $200–$400/year.' },
      { title: 'Confirm loss-of-use is at least 20% of dwelling', body: 'Loss-of-use covers temporary housing while your home is rebuilt. After major events, "temporary" can mean 12–24 months. 20% of dwelling is standard but in tight rental markets like the Bay Area or Boston, push to 30%.' },
    ],
    tips: [
      'Get a third-party rebuild estimate every 4–5 years. Construction costs jumped 38% from 2020–2025 nationally; your dwelling figure from 2020 is almost certainly too low.',
      'If your home is in an HOA or condo, your master policy covers the structure to a defined point ("walls-in" or "all-in"). Your HO-6 condo policy fills the gap — request the master policy declarations to know what gap you are filling.',
      'Old plumbing (galvanized steel, polybutylene) and old electrical (knob-and-tube, aluminum branch wiring, FPE/Zinsco panels) cause carriers to non-renew. Update before shopping; getting a quote with these flags is harder than getting one before they\'re documented.',
    ],
    faq: [
      { q: 'Should my dwelling coverage match my home\'s purchase price?', a: 'No. Purchase price includes the land, which does not need insuring. In coastal areas and dense metros, land can be 30–60% of total value. Use rebuild cost only — your insurer or a local appraiser can give you a current estimate.' },
      { q: 'Does standard home insurance cover floods or earthquakes?', a: 'Neither. Flood requires a separate NFIP policy or private flood carrier; earthquake requires a separate policy from the state plan (CEA in California) or a private carrier. About 90% of US natural-disaster losses involve at least one of these uncovered perils.' },
      { q: 'What is the difference between HO-3 and HO-5 policies?', a: 'HO-3 covers your dwelling on an "open perils" basis (anything not excluded) but personal property on a "named perils" basis (only specific listed events). HO-5 extends open-perils to personal property. HO-5 costs 5–15% more and is worth it if your contents value is substantial.' },
      { q: 'Will filing one home insurance claim raise my rate?', a: 'Usually yes, by 10–20%, and the surcharge typically lasts 3–5 years. Two claims in a 3-year window often triggers non-renewal. As a rule, do not file claims under $5,000 over your deductible — pay out of pocket and preserve the loss-free history.' },
      { q: 'Should I increase my home insurance deductible to save money?', a: 'Going from $1,000 to $2,500 typically saves 8–15% on premium. Going from $2,500 to $5,000 saves another 5–10%. The breakeven on $2,500 is about 6–8 years between claims, which most homeowners exceed.' },
    ],
    relatedTool: 'home-insurance-calculator',
    keywords: ['how much home insurance do i need', 'home insurance coverage amount', 'dwelling coverage calculator', 'replacement cost home insurance', 'homeowners insurance amounts'],
    publishedAt: '2026-05-09',
  },
  {
    slug: 'what-does-renters-insurance-cover',
    title: 'What Does Renters Insurance Cover? Plain-English Breakdown',
    query: 'what does renters insurance cover',
    metaDescription: 'Renters insurance covers personal property, liability, and loss-of-use — typically $12–$25/month. Here is what is and is not included, and how much coverage to buy.',
    intro: 'Renters insurance averages $185/year nationally and covers a lot more than most renters realize. It does not protect the building (your landlord\'s policy does that), but it covers your stuff, your liability, and your living costs if your unit becomes unlivable. Here is exactly what is and is not in a standard policy.',
    steps: [
      { title: 'Personal property: what is yours', body: 'Furniture, electronics, clothes, kitchen items, bikes, sporting goods, instruments. Coverage applies inside your unit and usually 10% of that limit anywhere in the world (laptop stolen on vacation = covered). Do an inventory — most renters underestimate their belongings by $8K–$15K until they walk through every drawer.' },
      { title: 'Liability: when you are at fault for damage to others', body: 'If you flood the unit below, your dog bites someone, or a guest trips on your rug and breaks an ankle, your liability coverage pays. Standard policies start at $100K; push to $300K for a few extra dollars per month.' },
      { title: 'Loss-of-use: covered displacement costs', body: 'If your unit becomes unlivable (fire, severe water damage, etc.), this covers hotel, restaurant meals above your normal grocery cost, laundromat, and storage. Usually capped at 30–40% of your personal property limit.' },
      { title: 'Medical payments to others', body: 'A small ($1K–$5K) no-fault coverage that pays medical bills for guests injured in your unit, regardless of liability. Useful for keeping minor incidents out of liability lawsuit territory.' },
      { title: 'What is NOT covered (the important list)', body: 'Flood (separate NFIP policy), earthquake (separate or endorsement), pest infestations, intentional damage, your roommate\'s belongings (unless they are on the policy), business equipment above $2,500–$5,000 sub-limit, cash and precious metals above $200, and most cyber/identity theft (separate add-on).' },
      { title: 'Choose replacement cost, not actual cash value', body: 'Replacement cost pays to buy a new equivalent item. Actual cash value pays depreciated value (your 5-year-old laptop = maybe $150). Replacement cost coverage costs 10–15% more and is worth every penny when you actually file a claim.' },
    ],
    tips: [
      'Most landlords now require a $100K–$300K liability minimum on renters policies. Read your lease; bring proof of coverage at signing or pay a "no insurance" surcharge of $20–$50/month plus a deposit increase.',
      'High-value items (engagement ring, professional camera, road bike, drum kit) usually need a scheduled rider above the $1,500 jewelry / $2,500 firearms / $1,000 cash sub-limits. Costs $5–$25/year per $1,000 of declared value.',
      'Bundle with your auto insurance for a 5–18% multi-policy discount — that often makes renters insurance effectively free or near-free.',
    ],
    faq: [
      { q: 'Is renters insurance worth it for $20/month?', a: 'Almost universally yes. The personal property coverage alone usually exceeds $30K, the liability coverage prevents wage garnishment from a single dog-bite or guest-injury claim, and loss-of-use covers hotel costs after fires and floods that would otherwise hit your savings hard.' },
      { q: 'Does renters insurance cover roommate belongings?', a: 'No, unless the roommate is named on the policy. Most carriers will not list unrelated roommates on the same policy — each roommate buys their own. A couple living together typically can share one policy.' },
      { q: 'Will my renters insurance cover my stuff in a storage unit?', a: 'Usually yes, at 10% of your personal property limit (so a $30K policy covers up to $3K in storage). For more, you need a storage-unit endorsement or a separate policy from the storage facility.' },
      { q: 'Does renters insurance cover bedbugs?', a: 'No. Pest infestations are universally excluded as a maintenance issue, and bedbugs specifically are typically the landlord\'s responsibility in most state landlord-tenant laws (varies by state).' },
      { q: 'How much renters insurance do I need?', a: 'Start with $25K–$40K personal property (do an honest inventory), $300K liability, and replacement cost coverage. Adjust personal property up if you have above-average electronics or specialty equipment. The cost difference between $25K and $50K of property coverage is usually $40–$80/year.' },
    ],
    relatedTool: 'renters-insurance-calculator',
    keywords: ['what does renters insurance cover', 'renters insurance coverage', 'is renters insurance worth it', 'how much renters insurance', 'renters insurance explained'],
    publishedAt: '2026-05-09',
  },
  {
    slug: 'cobra-vs-marketplace-which-is-cheaper',
    title: 'COBRA vs Marketplace: Which Is Cheaper After Job Loss?',
    query: 'cobra vs marketplace',
    metaDescription: 'Comparing COBRA continuation coverage vs ACA marketplace plans after job loss — premium math, network considerations, and the special enrollment window.',
    intro: 'Losing your job triggers two health insurance options: continue your employer plan via COBRA (typically $650–$2,400/month for a family) or switch to a marketplace plan during your 60-day special enrollment window. For most people, marketplace wins on cost — but COBRA wins for specific situations. Here is the framework.',
    steps: [
      { title: 'Get your actual COBRA quote in writing', body: 'COBRA costs the full premium plus a 2% admin fee. Your employer paid 70–85% of that while you worked there, so the COBRA bill is often 4–6× what was deducted from your paycheck. The HR letter you receive in the first 14 days has the exact number.' },
      { title: 'Estimate your marketplace subsidy', body: 'The ACA premium tax credit is based on household income for the year, not last year\'s. Estimate your full-year income including the gap (severance, unemployment, partial-year wages from new job). At 200% of FPL — about $31K single, $64K family of 4 — subsidies typically cover 70–90% of a Silver plan premium.' },
      { title: 'Compare networks, not just premiums', body: 'COBRA keeps your exact employer network. Marketplace plans (especially Silver and Bronze) often use narrow networks that exclude major hospital systems. If you are mid-treatment, mid-pregnancy, or have a specialist relationship, network continuity may justify the COBRA premium gap.' },
      { title: 'Check deductible and out-of-pocket reset', body: 'COBRA continues your same plan with the same deductible — including the portion you have already paid this year. A new marketplace plan resets the deductible to zero. If you have already hit $4,000 of a $5,000 deductible by August, COBRA for the rest of the year is often the better total-cost choice even if monthly premium is higher.' },
      { title: 'Use the 60-day special enrollment window strategically', body: 'After job loss, you have 60 days to enroll in a marketplace plan with retroactive coverage to the loss-of-coverage date. You also have 60 days to elect COBRA. You can wait, see if you have a medical event, and elect COBRA retroactively if needed — a free option with real value.' },
      { title: 'For 1–4 month gaps, consider short-term plans cautiously', body: 'Short-term medical insurance costs $100–$350/month but excludes pre-existing conditions and often does not cover prescription drugs or maternity. It is a stopgap for healthy single people, not a real substitute. ACA-compliant marketplace plans are almost always better for anyone with ongoing conditions.' },
    ],
    tips: [
      'If you have a Health Savings Account from a high-deductible employer plan, you can keep using the existing balance for medical expenses regardless of which option you choose — the HSA is yours forever.',
      'Severance pay counts as income for both subsidy calculation and COBRA election timing. If your severance includes employer-paid COBRA for 3–6 months, take it — that often beats marketplace for the period.',
      'You can switch from COBRA to marketplace at the next open enrollment, but not from marketplace back to COBRA mid-year. Pick carefully.',
    ],
    faq: [
      { q: 'How long does COBRA last?', a: 'Typically 18 months from your termination date, extending to 29 months if you become disabled, or 36 months for divorce/death-of-employee qualifying events. The end-of-COBRA date is itself a qualifying event for marketplace special enrollment.' },
      { q: 'Can I get an ACA subsidy if I quit my job voluntarily?', a: 'Yes. The marketplace does not care why you lost employer coverage — voluntary quit, layoff, or termination all trigger the same 60-day special enrollment window. Subsidies are based on income, not the reason for job change.' },
      { q: 'What if I find a new job in a few weeks — can I cancel COBRA?', a: 'Yes, you can drop COBRA mid-month or any time. If you elected and paid for COBRA but only used a few weeks, you eat that month\'s premium but face no penalty for stopping.' },
      { q: 'Will marketplace coverage be accepted by my doctor?', a: 'Depends on the specific plan. Marketplace plans use insurance networks (BCBS, Anthem, Kaiser, Oscar, etc.) — your doctor\'s acceptance depends on whether they take that network, not whether it came from the marketplace. Always verify before enrolling.' },
      { q: 'Is short-term health insurance the same as marketplace coverage?', a: 'No, and the difference is significant. Short-term plans can deny coverage for pre-existing conditions, exclude maternity, cap annual benefits, and do not satisfy the ACA. They are a budget bridge, not real coverage. Treat them like accidents-and-emergencies coverage only.' },
    ],
    relatedTool: 'cobra-vs-marketplace',
    keywords: ['cobra vs marketplace', 'cobra alternatives', 'health insurance after job loss', 'marketplace insurance after layoff', 'cobra cost vs aca'],
    publishedAt: '2026-05-09',
  },
  {
    slug: 'is-pet-insurance-worth-it',
    title: 'Is Pet Insurance Worth It? Real Cost-Benefit Math',
    query: 'is pet insurance worth it',
    metaDescription: 'When pet insurance pays off and when it does not — premium vs claim math, breed-specific risk, and the case for a pet emergency fund instead.',
    intro: 'Pet insurance averages $35–$70/month for dogs and $20–$40/month for cats in 2026. Whether it pays off depends almost entirely on breed, age at enrollment, and whether you would actually pay for $8,000 of unexpected vet care. Here is the math, with the cases where it wins and where a savings account beats it.',
    steps: [
      { title: 'Get your actual quote, not the "average"', body: 'Premiums vary 4× across breeds. A 1-year-old Maine Coon costs $25/month; a 1-year-old French Bulldog costs $95/month for the same policy. Same with dogs — Labs are cheap, brachycephalic breeds (Frenchies, Bulldogs, Pugs) and giant breeds (Great Danes, Mastiffs) are expensive.' },
      { title: 'Calculate lifetime cost of premiums', body: 'Premiums rise 8–15% per year, more steeply after age 8. For a Labrador adopted at 1 and insured for 12 years, expect $9,000–$13,000 in cumulative premiums. For a French Bulldog, $20,000–$28,000. Your insurance has to pay out more than that to come out ahead.' },
      { title: 'Compare to typical lifetime vet costs', body: 'Average lifetime vet spend for a dog: $11,000–$18,000 (more for large dogs and brachycephalic breeds). Cats: $6,000–$12,000. The insurance edge comes when one major event — TPLO surgery ($5K–$8K), cancer treatment ($8K–$20K), foreign body removal ($3K–$6K) — would otherwise be unaffordable.' },
      { title: 'Read the exclusions before enrolling', body: 'Pre-existing conditions are universally excluded. Most policies also exclude or limit hereditary conditions, dental disease, and behavioral treatment. Bilateral conditions (hip dysplasia in either hip) — if one side is pre-existing, the other side is often excluded too.' },
      { title: 'Pick reimbursement %, deductible, and annual cap', body: 'Standard configuration: 80% reimbursement, $500 deductible, $10,000 annual cap. Going to 90% reimbursement adds 15–20% to premium. Going to unlimited annual cap adds 10–25%. For peace-of-mind buyers, max it out; for cost-conscious, 80%/$500/$10K is usually plenty.' },
      { title: 'Consider a pet emergency fund instead', body: 'Saving $50/month from age 1 yields about $9,000 by age 10 (assuming 4% return). For healthy breeds with no chronic conditions, that fund covers most reasonable emergencies. Insurance wins for high-risk breeds; self-insurance often wins for low-risk breeds with disciplined savers.' },
    ],
    tips: [
      'Enroll while your pet is young and healthy. Conditions diagnosed before policy start are excluded forever — including conditions discovered at the wellness exam right before you buy the policy. Enroll first, then schedule the exam.',
      'Wellness add-ons (covering vaccines, routine exams, dental cleaning) are rarely worth it on the math. You pay $200–$400/year for benefits worth $250–$500. Skip them and put that money into savings.',
      'If you have multiple pets, ASPCA, Embrace, and Healthy Paws offer multi-pet discounts of 5–10%. Stack with annual-pay discounts (5–8%) for the cleanest savings.',
    ],
    faq: [
      { q: 'Does pet insurance cover pre-existing conditions?', a: 'Almost never. The industry-wide standard is to permanently exclude any condition that showed symptoms before policy start, even if undiagnosed. A few carriers (Embrace, Spot) will cover "curable" pre-existing conditions after a 12-month symptom-free period.' },
      { q: 'How does pet insurance reimbursement work?', a: 'You pay the vet directly, submit the invoice, and the insurer reimburses you 70–90% (your chosen percentage) after your deductible. Trupanion and a few others offer direct vet pay, but the standard model is reimbursement — you need cash flow to cover the bill upfront.' },
      { q: 'Should I get pet insurance for an older pet?', a: 'It gets harder and more expensive past age 8. Some carriers cap new enrollment at 14, others stop at 10. If your dog or cat is already 9+, the math usually favors a self-funded emergency fund unless you can get a cap-free policy.' },
      { q: 'What does pet insurance not cover?', a: 'Pre-existing conditions (universal), routine wellness (unless you add it), elective procedures, breeding costs, behavioral training (mostly), grooming, and food/supplements. Hereditary conditions are sometimes excluded; read the breed-specific exclusions in the policy.' },
      { q: 'Is pet insurance worth it for indoor cats?', a: 'Marginal. Indoor cats have low accident risk and most chronic illnesses (kidney disease, hyperthyroidism, diabetes) are manageable with $30–$80/month in care. Premiums of $20–$40/month rarely pay off across a lifetime. A $40/month savings account often beats insurance for indoor-only cats.' },
    ],
    relatedTool: 'pet-insurance-calculator',
    keywords: ['is pet insurance worth it', 'pet insurance cost', 'dog insurance worth it', 'cat insurance', 'pet insurance comparison'],
    publishedAt: '2026-05-09',
  },
  {
    slug: 'life-insurance-cost-by-age',
    title: 'How Much Does Life Insurance Cost by Age? (Real 2026 Quotes)',
    query: 'how much does life insurance cost by age',
    metaDescription: 'Term life insurance premiums by age 25, 35, 45, 55, 65 — for $250K, $500K, $1M coverage. Healthy non-smoker rates with worked examples.',
    intro: 'Term life insurance premiums roughly double every decade for the same coverage and same health rating. A healthy 30-year-old can lock in $500K of 20-year term for about $24/month; the same person waiting until 50 pays $96/month for the same policy. Here are real 2026 rates by age band, with the math on why locking in early is so valuable.',
    steps: [
      { title: 'Look up your rate band', body: 'A healthy non-smoker, 20-year level term, $500K coverage in 2026: age 25 = ~$20/month, age 30 = ~$24/month, age 35 = ~$30/month, age 40 = ~$42/month, age 45 = ~$60/month, age 50 = ~$96/month, age 55 = ~$165/month, age 60 = ~$285/month, age 65 = ~$520/month.' },
      { title: 'Apply the gender adjustment', body: 'Women pay 15–25% less than men for the same coverage and health rating because of longer life expectancy. The numbers above are blended; subtract ~20% for women, add ~5% for men.' },
      { title: 'Apply the smoker multiplier', body: 'Smokers pay 2.5–3.5× the non-smoker rate. A 35-year-old non-smoker at $30/month becomes a 35-year-old smoker at $90–$105/month for identical coverage. Most carriers reclassify after 12 months smoke-free — apply, then re-shop after a year off cigarettes.' },
      { title: 'Calculate the lock-in benefit', body: 'A 30-year-old buying $500K of 30-year term at $32/month locks that premium until age 60. The same person waiting until 40 pays $58/month for 30 years. Total premium difference over 30 years: $9,360 vs $20,880. The same coverage costs $11,520 more for waiting 10 years.' },
      { title: 'Layer multiple terms (laddering) to reduce total cost', body: 'Instead of one $1M / 30-year policy, buy $500K / 30-year + $500K / 20-year. Total premium drops 25–35% because the 20-year term is cheaper, and you only need the larger amount during the first 20 years (when kids are home, mortgage is unpaid).' },
      { title: 'Adjust for health rating', body: 'Carriers rate applicants Preferred Plus, Preferred, Standard Plus, Standard, or substandard (Table A–H). The numbers above are Preferred. Standard rates are typically 15–30% higher. Conditions like controlled type-2 diabetes, mild hypertension, or BMI 30+ usually push you to Standard or Standard Plus.' },
      { title: 'Re-shop every 5 years if your health improves', body: 'Quitting smoking, losing 30+ pounds, getting blood pressure or A1c under control — all common ways to drop a rating tier. New policies at the better tier often beat your existing policy even when accounting for being 5 years older.' },
    ],
    tips: [
      'Apply at the start of the calendar year you turn the next age. Most carriers age-rate based on "nearest birthday" — your 39th birthday rate applies for the 6 months before AND 6 months after.',
      'Get a real medical exam (paramed) instead of no-exam policies. No-exam coverage is 30–80% more expensive for healthy people, with limited benefit beyond convenience.',
      'Use an independent broker who shops 10+ carriers. Rates spread 60% across carriers for the same applicant — Banner, Lincoln, Pacific Life, AIG, and Protective tend to lead the market on healthy applicants.',
    ],
    faq: [
      { q: 'Why does life insurance get so much more expensive after 50?', a: 'Mortality risk roughly doubles each decade after 50. Carriers price for actual claim experience plus a margin, and the math forces sharp premium increases. By 65, the annual cost approaches what a savings buffer would cost — that is the natural endpoint of when term life makes sense.' },
      { q: 'Can I lock in a rate today and pay for it later?', a: 'No — premiums are paid as you go. But "level premium" terms (the standard) lock the monthly cost for the entire term length. A 30-year-old buying 30-year term at $32/month pays $32/month every month until age 60, even though the underlying mortality cost is rising each year.' },
      { q: 'Is no-exam life insurance worth the convenience?', a: 'For most healthy people, no. The convenience saves 1–3 weeks of underwriting time but costs 30–80% more in premium. For people with health conditions that would rate poorly with full underwriting, no-exam is sometimes the cheaper option after the rating adjustment.' },
      { q: 'How does a smoker quit-rate work?', a: 'After 12 months tobacco-free (most carriers; some require 24 or 36), you can apply for reclassification. Some carriers do this on the existing policy without re-underwriting; most require a new application. Going from smoker to non-smoker rates typically cuts premiums 50–60%.' },
      { q: 'Should I get whole life if I am older and term is expensive?', a: 'Usually not — whole life at 60+ is 8–15× the cost of term at the same coverage, and the cash value math gets worse with shorter remaining life expectancy. Better options: smaller term coverage matched to remaining obligations, or self-insurance via savings if your accumulated assets can cover survivor needs.' },
    ],
    relatedTool: 'life-insurance-calculator',
    keywords: ['life insurance cost by age', 'life insurance rates by age', 'how much does term life insurance cost', 'life insurance premium age', 'term life cost'],
    publishedAt: '2026-05-09',
  },
  {
    slug: 'do-i-need-umbrella-insurance',
    title: 'Do I Need Umbrella Insurance? (Asset-Based Decision Guide)',
    query: 'do i need umbrella insurance',
    metaDescription: 'Umbrella insurance is cheap (typically $200-$400/year for $1M) but only valuable if your assets exceed your standard liability limits. Decision framework and worked examples.',
    intro: 'A personal umbrella policy adds $1M–$5M of liability coverage on top of your auto and home insurance for typically $200–$400/year for the first million. The question is not whether umbrella is "worth it" in the abstract — it is whether you have enough assets to be worth protecting beyond your standard policy limits.',
    steps: [
      { title: 'Calculate your protectable net worth', body: 'Add up: home equity, retirement accounts (401k/IRA — partly protected federally but partially exposed in some states), taxable investments, savings accounts, vehicles, and your future earning capacity (lawyers count this in lawsuit collection). Most homeowners with full-time income have $300K–$2M of protectable assets without realizing it.' },
      { title: 'Check your current liability limits', body: 'Your auto policy probably has bodily injury liability of 100/300 ($100K per person, $300K per accident) or lower. Your homeowners liability is usually $100K–$300K. If a serious accident or premises lawsuit exceeds these limits, the difference comes from your assets — house, savings, retirement.' },
      { title: 'Run the threshold calculation', body: 'If your protectable net worth exceeds your auto + home liability limits combined (e.g., $200K assets vs $400K limits = no umbrella needed; $800K assets vs $400K limits = umbrella valuable), you have exposure umbrella would cover.' },
      { title: 'Account for high-risk profile factors', body: 'Things that raise your liability exposure: teen drivers in the household (3–5× higher accident frequency), swimming pool ("attractive nuisance"), trampoline, dog of a breed insurers flag, rental property, frequent hosting of large groups, sports coaching role, public profile (more lawsuit-attractive). Each pushes umbrella from optional toward needed.' },
      { title: 'Confirm your auto + home meet umbrella underwriting minimums', body: 'Most umbrella carriers require 250/500 auto liability and $300K homeowners liability before they will write coverage. If your limits are below these floors, you need to raise them first — typically adds $80–$200/year before adding the umbrella itself.' },
      { title: 'Get the umbrella quote', body: '$1M umbrella through an established carrier (Allstate, State Farm, USAA, Geico, RLI standalone) typically costs $200–$400/year. Each additional $1M is $100–$200. $5M total coverage usually lands in the $700–$1,200/year range.' },
      { title: 'Bundle for savings if possible', body: 'Umbrella from your existing auto/home carrier usually costs 20–40% less than a standalone umbrella from a separate company. The bundle savings often pays for the umbrella itself versus a non-bundled approach.' },
    ],
    tips: [
      'Umbrella is one of the highest-leverage insurance purchases in personal finance. The cost-per-coverage ratio is ~$0.0002 per dollar of liability protection — orders of magnitude cheaper than auto or home.',
      'If you switch primary auto carriers, your umbrella usually has to follow (umbrella sits on top of the auto liability). Re-shop the umbrella when you switch auto.',
      'Umbrella covers libel, slander, and false-imprisonment claims that auto/home policies do not. For people with public-facing roles or active social media, this is a real value-add.',
    ],
    faq: [
      { q: 'Is umbrella insurance worth it for someone with $200,000 net worth?', a: 'Marginally. If your auto liability is 100/300 and home is $300K, you already have $400K+ of liability coverage — close to your protectable assets. The umbrella starts becoming clearly worth it around $500K+ net worth or with high-risk profile factors (teen driver, pool, dog with bite history).' },
      { q: 'Does umbrella insurance cover business activities?', a: 'No. Personal umbrella explicitly excludes business and professional liability. If you have a side business, freelance work, or rental property, you need separate business liability or landlord insurance for those activities.' },
      { q: 'How much umbrella do I need?', a: 'Common rule of thumb: at least equal to your protectable net worth. For most middle-class homeowners, $1M is enough. Above $2M net worth, push to $2M–$3M umbrella. Above $5M net worth, look at excess liability through a high-net-worth carrier (Chubb, AIG Private Client) for $5M+ coverage.' },
      { q: 'Does umbrella insurance affect my credit score?', a: 'No, the policy itself does not. The application may include a soft credit pull which is invisible to lenders. The premium is not reported to credit bureaus.' },
      { q: 'Can I get umbrella insurance without home or auto with the same carrier?', a: 'Yes, but it is harder. Standalone umbrella from RLI, Berkley, or USAA is straightforward. Most other carriers strongly prefer to bundle — they will quote standalone but at notably higher rates.' },
    ],
    relatedTool: 'umbrella-insurance-calculator',
    keywords: ['do i need umbrella insurance', 'umbrella insurance cost', 'how much umbrella insurance', 'umbrella policy worth it', 'personal umbrella insurance'],
    publishedAt: '2026-05-09',
  },
  {
    slug: 'how-much-disability-insurance-do-i-need',
    title: 'How Much Disability Insurance Do I Need?',
    query: 'how much disability insurance do i need',
    metaDescription: 'Long-term disability insurance replaces 60-70% of income. How to size your policy, decide between own-occupation and any-occupation, and avoid the elimination-period trap.',
    intro: 'Long-term disability is the biggest gap in most household insurance plans. About 25% of working-age Americans will experience a disability lasting 90+ days at some point in their career, and the average claim lasts 31.6 months. Most people are vastly underinsured because they assume Social Security Disability or employer short-term disability will cover them — neither does.',
    steps: [
      { title: 'Calculate your monthly need', body: 'Aim to replace 60–70% of pre-tax income. If you earn $7,000/month, target $4,200–$4,900 of monthly disability benefit. This accounts for the fact that disability benefits paid from after-tax-funded policies are tax-free, so 60–70% of gross matches close to 100% of net.' },
      { title: 'Subtract employer-provided coverage', body: 'Most employer LTD plans pay 50–60% of base salary, capped at $5,000–$15,000/month. Find your plan summary. The gap between what employer LTD pays and your 60–70% target is what you need to buy individually.' },
      { title: 'Choose own-occupation vs any-occupation', body: 'Own-occupation pays if you cannot do YOUR specific job (a surgeon who can no longer perform surgery still gets benefits even if she can teach). Any-occupation pays only if you cannot do ANY job your training fits. Own-occupation costs 30–60% more but is the right call for high-skill professionals — the definition of "disabled" is far easier to meet.' },
      { title: 'Set the elimination period to match your savings', body: 'Elimination period (the deductible-equivalent for disability) is typically 30, 60, 90, 180, or 365 days. Each step longer cuts the premium 15–25%. Standard recommendation: match the elimination period to your liquid savings — 90 days if you have 3 months of expenses, 180 days if 6 months.' },
      { title: 'Pick the benefit period', body: 'Common choices: 2-year, 5-year, 10-year, to-age-65, to-age-67. To-age-65 (or 67) is the standard for primary working-age coverage. Premium increases ~15–25% from 5-year to to-age-65, but the protection from a permanent disability claim is dramatically better.' },
      { title: 'Add cost-of-living adjustment (COLA) rider', body: 'Without COLA, your $5,000/month benefit is $5,000/month forever — even 25 years into a claim. With COLA (typically 3% annual), the benefit grows with inflation. Adds 15–25% to premium but is essential for claims that may last decades.' },
      { title: 'Compare 3+ carriers', body: 'Disability insurance pricing varies more than life insurance — same applicant can see 50%+ premium spread across carriers. Top names: Guardian, Principal, Standard, MassMutual, Ameritas. Use an independent broker who shops at least 4 carriers.' },
    ],
    tips: [
      'Buy young. A 30-year-old in good health pays $40–$80/month for $5,000 of monthly disability benefit; a 50-year-old pays $180–$280 for the same coverage.',
      'Premiums you pay yourself create tax-free benefits at claim time. Premiums paid by your employer create taxable benefits. If your employer offers LTD as a tax-free voluntary benefit you pay for, take it.',
      'Some occupations (physicians, lawyers, dentists) have specialty carriers that price more aggressively — Berkshire Mutual, Principal Life Specialty Markets, Standard Disability.',
    ],
    faq: [
      { q: 'Will Social Security Disability cover me if I cannot work?', a: 'Probably not. SSDI requires you to be unable to perform ANY substantial work, not just your specific job. Approval rates on initial applications are 30–35%, and the average benefit is about $1,500/month — well below most working-age income needs. Treat SSDI as a backstop, not primary coverage.' },
      { q: 'How long do disability claims typically last?', a: 'Average claim duration is 31.6 months according to the Council for Disability Awareness. Roughly 1 in 7 claims becomes permanent. The longer the claim, the more valuable a to-age-65 benefit period becomes vs a 5-year or 10-year cap.' },
      { q: 'Is short-term disability worth buying separately?', a: 'Usually no for individual purchase. Short-term disability is typically only worth it through an employer voluntary plan (heavily subsidized). For personal short-term coverage, an emergency fund of 3–6 months of expenses is the cheaper and more flexible answer.' },
      { q: 'Does disability insurance cover mental health and substance abuse?', a: 'Most policies cap coverage for mental and nervous conditions at 24 months total benefit. Substance abuse is usually limited to 12–24 months. Some carriers offer full mental-health coverage as a higher-cost rider — worth considering for professionals in stress-heavy fields.' },
      { q: 'Can I deduct disability insurance premiums on my taxes?', a: 'Personal disability premiums are not deductible. Business owners deducting LTD premiums for themselves on a business return turn the future benefits into taxable income. Almost always better to pay personal-side and get tax-free benefits.' },
    ],
    relatedTool: 'disability-insurance-calculator',
    keywords: ['how much disability insurance do i need', 'disability insurance coverage', 'long term disability insurance', 'own occupation disability', 'disability insurance amount'],
    publishedAt: '2026-05-09',
  },
  {
    slug: 'is-travel-insurance-worth-it',
    title: 'Is Travel Insurance Worth It? (Real Cost-Benefit Math)',
    query: 'is travel insurance worth it',
    metaDescription: 'When travel insurance pays off — trip cost threshold, medical-only vs comprehensive, credit card coverage you already have, and the cancel-for-any-reason upgrade.',
    intro: 'Travel insurance costs 4–12% of total trip cost depending on coverage level and traveler age. The question is whether the protection beats what your credit card already provides for free. For most domestic US trips under $2,000, no. For international trips, cruises, or trips with non-refundable deposits over $3,000, usually yes.',
    steps: [
      { title: 'List what you have already', body: 'If you booked the trip on a major rewards credit card (Chase Sapphire, Amex Platinum, Citi Premier, Capital One Venture), you likely have automatic trip cancellation/interruption coverage of $5,000–$10,000 per trip and primary rental car coverage. Pull your card benefits guide before paying for travel insurance.' },
      { title: 'Calculate non-refundable trip cost', body: 'Travel insurance premium is based on what you would lose if you canceled. Refundable airfare and free-cancel hotels do not count. Pre-paid tours, non-refundable resort stays, cruise deposits, event tickets — these are what the policy covers. If your non-refundable total is under $1,000, the policy rarely pencils out.' },
      { title: 'Pick basic vs comprehensive', body: 'Basic plans (~4–6% of trip cost) cover trip cancellation, interruption, and emergency medical. Comprehensive plans (~7–12%) add baggage, travel delay, missed connection, and rental car coverage. For domestic trips, basic is usually enough; for international, go comprehensive.' },
      { title: 'Add cancel-for-any-reason (CFAR) if relevant', body: 'Standard cancellation only covers listed reasons (illness, death in family, weather, etc.). CFAR adds a 75% refund for canceling for ANY reason — change of mind, work conflict, personal preference. Adds 40–60% to the premium and must usually be purchased within 14–21 days of booking. Worth it for high-uncertainty trips.' },
      { title: 'Verify medical coverage abroad', body: 'US health insurance often does not cover international care, or covers it as out-of-network with massive coinsurance. Travel medical coverage of $50,000–$100,000 per trip costs $30–$80 for a 1-week trip — minimal cost for catastrophic protection. Includes medical evacuation, which can run $50,000–$250,000 for a serious case.' },
      { title: 'Skip if your trip is short, cheap, and domestic', body: 'A $400 weekend in another US city: not worth insuring. A $1,200 domestic flight + hotel for a week: probably not worth it (credit card coverage handles cancellation; US health insurance covers medical). Crossover point is usually trip cost $2,500+ AND non-refundable component $1,500+ AND international destination.' },
    ],
    tips: [
      'Buy within 14–21 days of the first trip deposit to access pre-existing condition waivers, CFAR option, and "financial default of supplier" coverage. After that window, these features are unavailable on most policies.',
      'Compare InsureMyTrip, Squaremouth, or TravelInsurance.com for quotes — these aggregators show 15–30 carrier quotes in one place.',
      'For frequent travelers, an annual multi-trip policy beats per-trip pricing once you take 3+ trips per year. Costs $300–$700/year and covers unlimited trips up to 30 days each.',
    ],
    faq: [
      { q: 'Does my credit card replace travel insurance?', a: 'Partially. Premium travel cards (Chase Sapphire Reserve, Amex Platinum, etc.) cover trip cancellation/interruption up to $5K–$10K, baggage delay, and primary rental car coverage. They do NOT cover emergency medical abroad, medical evacuation, or pre-existing-condition exclusions for cancellation. For international trips, the card is necessary but not sufficient.' },
      { q: 'Is travel insurance worth it for a cruise?', a: 'Almost always yes. Cruise lines have aggressive cancellation policies (often 50% penalty 90 days out, 100% penalty 30 days out) and onboard medical evacuation runs $50K–$200K. A comprehensive policy at 7–10% of cruise cost is cheap insurance against the unique cancellation and medical risks.' },
      { q: 'Can I buy travel insurance after I leave for the trip?', a: 'Most policies require purchase before departure. A few carriers (World Nomads is the best-known) sell insurance after travel begins, primarily for backpackers extending trips abroad. Pre-existing condition waivers, CFAR, and trip-cancellation are not available for after-departure purchases.' },
      { q: 'Does travel insurance cover COVID-19 cancellations?', a: 'Most current policies treat COVID like any other illness — you are covered if YOU test positive and cannot travel, but not for general fear of COVID. CFAR is the only path to canceling for "I do not want to risk it." Verify the specific exclusion language in the policy.' },
      { q: 'What is the difference between "trip cancellation" and "trip interruption"?', a: 'Cancellation pays before the trip starts (you cancel for a covered reason, get refunded for non-refundable costs). Interruption pays after the trip starts (you have to come home early or extend the trip for a covered reason — covers extra travel costs and unused trip portions).' },
    ],
    relatedTool: 'travel-insurance-calculator',
    keywords: ['is travel insurance worth it', 'travel insurance cost', 'cancel for any reason travel insurance', 'travel medical insurance', 'cruise travel insurance'],
    publishedAt: '2026-05-09',
  },
  {
    slug: 'high-deductible-vs-low-deductible',
    title: 'High Deductible vs Low Deductible: Which Saves More?',
    query: 'high deductible vs low deductible',
    metaDescription: 'Auto and home insurance deductible breakeven math. When higher deductibles save money and when they backfire — with real premium-savings tables.',
    intro: 'Picking between a $500 and $2,500 deductible saves $80–$320 per year in premium for auto, $200–$600 per year for home. The breakeven question: how often do you actually file claims? For most safe drivers and homeowners, higher deductibles win on math by a wide margin. Here is the framework.',
    steps: [
      { title: 'Get current premium quotes at multiple deductible levels', body: 'Most carriers will quote at $250, $500, $1,000, $2,500, $5,000 deductibles in one shot. Ask for the quote table — typical spread for a 35-year-old driver: $250 ded = $1,650/yr, $500 = $1,520/yr, $1,000 = $1,420/yr, $2,500 = $1,290/yr.' },
      { title: 'Calculate annual premium savings per step', body: 'From the table above: going from $500 to $1,000 saves $100/year. Going from $1,000 to $2,500 saves $130/year. The savings get smaller per dollar of deductible at higher tiers, but they compound — every year you do not claim, you keep the savings.' },
      { title: 'Calculate the breakeven', body: 'Going from $500 to $2,500 deductible saves $230/year ($1,520 - $1,290) but you would owe $2,000 more out of pocket if you filed a claim. Breakeven: $2,000 / $230 = 8.7 years between claims. Most safe drivers go 10–15+ years between at-fault claims, easily clearing the breakeven.' },
      { title: 'Account for your actual claim history', body: 'Pull your CLUE report (free annually at LexisNexis). Count claims in the last 10 years. Zero claims = aggressive higher deductible strongly favored. 1 claim = moderate higher deductible OK. 2+ claims = stay at standard $500–$1,000 deductible until you have a clean stretch.' },
      { title: 'Match the deductible to your liquid savings', body: 'Pick a deductible you can comfortably write a check for tomorrow. If $2,500 surprise expense would force you onto a credit card, your deductible is too high regardless of the math. Most personal-finance recommendations: pick the deductible equal to roughly 1–2% of annual income up to a maximum of $5,000.' },
      { title: 'Adjust for vehicle/property value', body: 'A $1,000 deductible on a $5,000 car is 20% of value — too high relative to risk. Same $1,000 on a $35,000 car is 3% of value — appropriate. For older vehicles, the deductible should drop proportionally; for newer, it can rise.' },
      { title: 'Re-evaluate every 2–3 years', body: 'Your savings build, your driving record improves (or worsens), the carrier raises base rates. The optimal deductible shifts with each. Re-quote at multiple tiers when you renew, every 2–3 years minimum.' },
    ],
    tips: [
      'Some carriers offer a "vanishing deductible" — your deductible drops $50–$100/year you go without a claim. Useful but rarely the cheapest option overall; the base premium is usually higher.',
      'Home insurance deductibles are sometimes percentage-based (1%, 2%, 5% of dwelling coverage) rather than dollar amounts. A 1% deductible on $400K coverage is $4,000. Read the policy carefully.',
      'Hurricane and earthquake deductibles are often separate and much higher (5–10% of dwelling). Coastal homeowners frequently overlook this until a claim arrives.',
    ],
    faq: [
      { q: 'Should I file a small claim at my deductible?', a: 'Usually no. Most insurers raise rates 10–25% for 3 years after any claim, even small ones. A $700 claim at $500 deductible nets you $200 — and the rate increase typically costs $300–$700 over 3 years. Pay out of pocket and preserve loss-free history.' },
      { q: 'Does a higher deductible always mean lower premium?', a: 'Yes, but the savings curve flattens at very high deductibles. Going from $1,000 to $2,500 saves more per dollar than $5,000 to $10,000. Most insurers stop offering meaningful additional savings above $2,500–$5,000.' },
      { q: 'Can I change my deductible mid-policy?', a: 'Yes, usually within 30–60 days of any major life event (move, vehicle change, mortgage refinance). Outside those windows, most carriers allow changes at renewal. Some allow mid-term changes on request — call to ask.' },
      { q: 'What if I cannot afford my deductible at claim time?', a: 'Most carriers do not finance the deductible — you owe it before they pay anything. Some auto repair shops offer no-interest payment plans for the deductible portion. Ideally, keep the deductible amount in your liquid savings as an "insurance emergency fund."' },
      { q: 'Is the deductible the same for collision and comprehensive?', a: 'No, you set them separately. Comprehensive (theft, weather, glass) is often set lower than collision because comp claims are more frequent. A common pairing: $500 comp / $1,000 collision — covers most realistic losses while saving 5–10% on premium vs $250 / $500.' },
    ],
    relatedTool: 'deductible-calculator',
    keywords: ['high deductible vs low deductible', 'insurance deductible amount', 'best deductible amount', 'deductible vs premium', 'how to choose deductible'],
    publishedAt: '2026-05-09',
  },
  {
    slug: 'do-i-need-flood-insurance',
    title: 'Do I Need Flood Insurance? (NFIP + Private Options)',
    query: 'do i need flood insurance',
    metaDescription: 'Standard home insurance does not cover floods. Who needs NFIP coverage, when private flood beats NFIP, and the 30-day waiting period gotcha.',
    intro: 'Standard homeowners insurance does not cover floods — not even one inch of water from a backed-up creek, a burst dam, or hurricane storm surge. Roughly 25% of US flood claims occur outside designated high-risk zones. Understanding your real risk and getting coverage before you need it (there is a 30-day waiting period on most policies) is critical.',
    steps: [
      { title: 'Check your FEMA flood zone', body: 'Go to msc.fema.gov/portal/home, enter your address, and find your flood zone. Zones A, AE, AH, AO, AR, A99, V, VE = high-risk (Special Flood Hazard Area). Zones B, X (shaded), X (unshaded) = moderate to low risk. Mortgages on properties in high-risk zones legally require flood insurance.' },
      { title: 'Calculate your real exposure', body: 'High-risk zones (1% annual flood probability) have a 26% chance of flooding during a 30-year mortgage. Moderate zones (0.2% annual) have a 6% chance over 30 years. Even "low-risk" carries 1–3% lifetime probability — enough to consider $300–$500/year coverage.' },
      { title: 'Get an NFIP quote', body: 'NFIP (National Flood Insurance Program) is the federal flood insurance program. Quote any agent who writes home insurance — most will quote it for you. Coverage caps: $250,000 building + $100,000 contents for residential. Premiums range $400–$3,500/year depending on zone, elevation, and construction.' },
      { title: 'Compare to private flood insurance', body: 'Private flood (Neptune, Wright, FloodPro, AssuredPartners flood program) often beats NFIP on price for moderate-to-low-risk properties. Sometimes 30–50% cheaper. Coverage limits are higher (up to $1M+ vs NFIP $250K). Downside: private carriers can non-renew after a claim, while NFIP cannot.' },
      { title: 'Plan for the 30-day waiting period', body: 'Most flood policies (NFIP and private) have a 30-day waiting period before coverage starts. Buying a policy when a hurricane is 2 days out does not work. Buy before storm season begins, not when forecasts get scary.' },
      { title: 'Add Increased Cost of Compliance (ICC) coverage', body: 'NFIP includes up to $30,000 of ICC coverage — pays to elevate, demolish, or relocate damaged structures to comply with current floodplain rules. Private flood may or may not include this; check the policy. After Katrina and Sandy, many homeowners discovered ICC was the only thing that made rebuilding affordable.' },
      { title: 'Know what flood insurance excludes', body: 'Detached structures (sheds, garages — separate building coverage often required), basement contents (NFIP covers structural elements only — drywall, furnace), landscaping, currency, precious metals, vehicles (your auto insurance comp covers flood-damaged vehicles, not flood policy).' },
    ],
    tips: [
      'Renters in flood-prone areas should buy NFIP contents-only coverage. Often $80–$200/year for $20K–$40K of contents protection. Renters insurance does not cover flood.',
      'Elevation certificates dramatically lower premiums in high-risk zones. Costs $400–$700 to get one from a licensed surveyor; can drop annual premium by $1,000+ for properties built above the base flood elevation.',
      'FEMA flood zones get re-mapped roughly every 5 years. Your "low-risk" property could be re-zoned high-risk at the next map cycle, suddenly requiring coverage. Check the proposed map updates at fema.gov.',
    ],
    faq: [
      { q: 'Is flood insurance required by law?', a: 'For mortgaged properties in FEMA-designated high-risk zones, yes — federally-backed mortgages (most US mortgages) require flood insurance. Outside high-risk zones, it is optional but often recommended.' },
      { q: 'Does my homeowners insurance cover any flood damage?', a: 'No. Homeowners insurance specifically excludes flooding. It does cover other water damage (burst pipes, accidental overflow from appliances, roof leaks) but not water that comes from outside the home (rising creeks, storm surge, sewer backup from external sources).' },
      { q: 'How much does flood insurance cost?', a: 'NFIP averages: low-risk zone $500–$700/year, moderate-risk $700–$1,200, high-risk $1,200–$3,000, very high-risk (V zones) $2,500–$6,000+. Private flood often runs 20–40% less for moderate and low-risk properties.' },
      { q: 'Why is there a 30-day waiting period?', a: 'To prevent adverse selection — buying coverage right before a known flood event. Exceptions: lender-required coverage at mortgage closing has no waiting period; some private carriers offer immediate coverage but at higher premiums.' },
      { q: 'Will federal disaster aid replace flood insurance?', a: 'No. FEMA disaster assistance after a presidential disaster declaration is typically a low-interest SBA loan (not a grant) with maximum payout caps far below typical damage costs. Buying flood insurance is dramatically cheaper than relying on disaster aid.' },
    ],
    relatedTool: 'flood-insurance-calculator',
    keywords: ['do i need flood insurance', 'nfip flood insurance', 'flood insurance cost', 'flood zone insurance', 'flood insurance vs homeowners'],
    publishedAt: '2026-05-09',
  },
  {
    slug: 'small-business-insurance-coverage-guide',
    title: 'Small Business Insurance: What Coverage Do You Need?',
    query: 'small business insurance',
    metaDescription: 'General liability, commercial property, professional liability, and workers comp — sizing each coverage for solo operators, small teams, and growing businesses.',
    intro: 'Small business insurance breaks into 4–6 distinct policy types depending on your operation. A solo consultant needs different coverage than a 12-employee restaurant. Most "business insurance is too expensive" complaints come from buying the wrong combinations. Here is the layered approach with realistic 2026 pricing.',
    steps: [
      { title: 'Layer 1 — General Liability (almost everyone)', body: 'Covers third-party bodily injury and property damage. If a client trips in your office or your contractor work damages a client property, this pays. Standard coverage is $1M per occurrence / $2M aggregate, costs $400–$1,200/year for a solo operator, $1,200–$3,500 for a small team. Required by most commercial leases and B2B contracts.' },
      { title: 'Layer 2 — Commercial Property (if you own/rent space or equipment)', body: 'Covers your business location, equipment, inventory. Replacement cost varies wildly by what you own. A consultant with a laptop: optional. A bakery with $80K in ovens: essential, expect $800–$2,000/year. Bundled with general liability as a Business Owners Policy (BOP) for 10–25% savings vs separate.' },
      { title: 'Layer 3 — Professional Liability / E&O (knowledge-work businesses)', body: 'Covers claims of negligence in professional services rendered. Consultants, IT services, accountants, designers, architects, real estate agents need this. General liability does NOT cover professional advice claims. Costs $500–$2,500/year for solo operators depending on profession and revenue.' },
      { title: 'Layer 4 — Workers Compensation (any W-2 employees)', body: 'Required by law in 49 states (Texas optional) for any business with employees. Covers medical and lost wages for work-related injuries. Cost varies by state, payroll, and risk class — office workers $0.30–$0.80 per $100 payroll, construction $5–$15 per $100 payroll. Solo operators with no employees usually exempt; 1099 contractors are not employees but check your state rules.' },
      { title: 'Layer 5 — Cyber Liability (handling customer data)', body: 'Covers data breach response, ransomware, business interruption from cyber events. Critical if you handle customer PII, payment data, or healthcare info. Costs $500–$3,000/year for small businesses. Many B2B contracts now require this — read the contract.' },
      { title: 'Layer 6 — Commercial Auto (vehicles used for business)', body: 'Personal auto policies exclude most business use. If you drive between client sites, deliver products, or have a company vehicle, you need commercial auto. $800–$2,500/year per vehicle, often higher than personal auto due to commercial use risk.' },
      { title: 'Use a Business Owners Policy (BOP) bundle', body: 'A BOP combines general liability + commercial property + business interruption insurance for small-to-medium businesses. Typically saves 10–25% vs separate policies. Most appropriate for service businesses, retail, light manufacturing, and most professional offices.' },
    ],
    tips: [
      'Insurers like Hiscox, Next Insurance, and Coterie specialize in micro-business and solo operators with online quote-bind-purchase flows. Often beat traditional carriers on price for solo and 1–5 person businesses.',
      'Many states require workers comp even for the owner-only operating their own corporation. Check your state — failing to carry required coverage triggers penalties of $1,000+/day plus personal liability for any injury.',
      'Annual revenue tier dramatically affects pricing. Most insurers have rate breaks at $50K, $250K, $1M, $5M revenue. A consultant claiming $80K revenue pays meaningfully more than one claiming $40K, even at the same coverage level.',
    ],
    faq: [
      { q: 'How much does small business insurance cost?', a: 'Solo operator with general liability + commercial property + professional liability typically pays $1,500–$3,500/year total. Small business with 5–10 employees including workers comp typically pays $5,000–$15,000/year total. Construction, food service, and healthcare businesses cost meaningfully more.' },
      { q: 'Do I need business insurance as a sole proprietor?', a: 'Yes, especially general liability and professional liability if you give advice. Sole proprietorship offers no personal asset protection — without insurance, business lawsuits attack your personal savings, home, and retirement. The $400–$1,200/year for general liability is cheap protection.' },
      { q: 'Do I need workers comp for 1099 contractors?', a: 'Generally no, but state rules vary and carriers sometimes require it anyway. Some states (CA, MA, NY) treat misclassification of employees as 1099 as a serious offense. If your contractors look more like employees than independent businesses, consult an employment attorney before skipping workers comp.' },
      { q: 'Can my home insurance cover my home-based business?', a: 'Usually not, beyond a small endorsement. Most homeowners policies cover up to $2,500 of business equipment and zero business liability. For meaningful coverage, you need a home-based business endorsement ($50–$200/year extension) or a separate small business policy.' },
      { q: 'What is the most important small business insurance?', a: 'General liability for almost everyone, then professional liability if you give advice for money, then workers comp if you have W-2 employees. These three cover the highest-frequency severity-loss events for most small businesses.' },
    ],
    relatedTool: 'business-insurance-calculator',
    keywords: ['small business insurance', 'business insurance cost', 'general liability insurance small business', 'professional liability insurance', 'business owners policy'],
    publishedAt: '2026-05-09',
  },
  {
    slug: 'how-to-compare-car-insurance-quotes',
    title: 'How to Compare Car Insurance Quotes (Apples to Apples)',
    query: 'how to compare car insurance quotes',
    metaDescription: 'The 7-point checklist for comparing car insurance quotes correctly — coverage levels, deductibles, exclusions, and the discount stacking that determines real cost.',
    intro: 'Most "car insurance comparison" results are useless because the quotes are not comparing the same thing. One carrier shows $89/month with state minimums, another shows $145/month with full coverage at higher limits. Here is how to compare carriers correctly so you actually identify the best deal.',
    steps: [
      { title: 'Lock down identical coverage limits across all quotes', body: 'Pick your target liability (e.g., 100/300/100), uninsured motorist (matched to liability), comprehensive deductible ($500), collision deductible ($1,000), and any add-ons (rental car, roadside, gap). Use these EXACT same numbers when getting each quote. Different limits = useless comparison.' },
      { title: 'Get quotes from 4 carrier categories', body: 'Direct online (Geico, Progressive, Esurance), captive agents (State Farm, Allstate, Farmers), independent broker (carries multiple carriers — Liberty, Travelers, Nationwide, Erie, Auto-Owners), and one specialty (USAA if eligible, Amica, NJM regional, Wawanesa). Spreads typically 60–120% across categories for the same driver.' },
      { title: 'Apply the same discount stack', body: 'Confirm each carrier applied: paid-in-full discount (4–10%), paperless discount (1–3%), telematics enrollment (often quoted separately, 10–30%), defensive driving course (5–10% if completed), home/auto bundle (10–22% if applicable), low annual mileage discount (5–15% under 7,500/year). Differences in applied discounts can swing the apparent price by 30%.' },
      { title: 'Verify the rate is from the same vehicle and ZIP', body: 'Quote tools sometimes default to base ZIP+vehicle assumptions. Make sure each quote uses your exact garaging ZIP, exact vehicle (year/make/model/trim/VIN), exact use (commute miles, business use yes/no). A 2-mile difference in commute distance can swing rate 5–10%.' },
      { title: 'Read the policy form, not just the price', body: 'OEM parts vs aftermarket on collision claims, accident forgiveness inclusion, rental car coverage limits ($30/day vs $50/day), towing coverage, glass deductible (full or matches collision deductible). Cheap carriers often save money by tightening these. Compare the actual policy documents, not just the bottom-line price.' },
      { title: 'Check carrier financial strength + claim handling', body: 'Look up A.M. Best ratings (A or A+ minimum acceptable) and JD Power claim satisfaction scores. The cheapest carrier with C+ rating and 700/1000 claim score is not actually the cheapest if your first claim takes 8 weeks and shorts you 30% on the settlement. Top claim-satisfaction carriers in 2026: Amica, USAA, Erie, NJM, Auto-Owners.' },
      { title: 'Re-quote every 2–3 years', body: 'Insurer pricing models drift. The carrier that beat the field by 20% three years ago may now be 10% above market. Re-quote every 2–3 years even if you are happy — competition keeps your rate honest.' },
    ],
    tips: [
      'Most carriers will price-match if you bring a competitor quote; about 30–40% will reduce 5–10%. Bring the actual quote document, not just a verbal "I saw $X elsewhere."',
      'Rate increases at renewal are often 5–15% for "loyalty tax" reasons, even if your driving record improved. Re-shopping at every other renewal protects against this.',
      'Multi-line discounts are often inflated in quotes vs reality. The bundled discount might appear as 22% in the quote but the underlying home insurance rate is set 15% above market — net is 7%, not 22%. Always compare each line separately as well as bundled.',
    ],
    faq: [
      { q: 'How many car insurance quotes should I get?', a: 'Minimum 4, ideally 6–8. The rate spread for the same driver across 8 carriers commonly hits 80–120%. Stopping at 2 quotes leaves significant savings on the table.' },
      { q: 'Will getting multiple insurance quotes hurt my credit?', a: 'Insurance shopping uses soft credit pulls in most states, which do not affect your credit score. A few states (Massachusetts, California in some cases) prohibit credit-based rating entirely. Insurance shopping is far less credit-impactful than loan or credit card shopping.' },
      { q: 'Should I switch carriers for $20/month savings?', a: 'Depends on the math. $20/month = $240/year. Over 5 years that is $1,200 saved. Worth it if the new carrier has equal or better claim service. Not worth it if you are switching from a top-tier claim carrier (USAA, Amica, Erie) to a budget carrier (mid-tier claims service).' },
      { q: 'What is the "honeymoon" period in auto insurance?', a: 'New customers often get a 6–12 month introductory rate. At first or second renewal, rates jump 10–25% to "true" pricing. Many cheap initial quotes are honeymoon rates. Ask the agent: "Is this a new-customer rate or a renewal rate?"' },
      { q: 'How often does car insurance change rates?', a: 'Most carriers refile rates every 6–12 months with state insurance departments. Your individual rate can change at every 6-month renewal. Catastrophe years (heavy hurricanes, hail seasons) often trigger 8–15% rate increases at next renewal even for unaffected policyholders.' },
    ],
    relatedTool: 'car-insurance-comparison',
    keywords: ['how to compare car insurance quotes', 'car insurance comparison', 'compare auto insurance', 'cheapest car insurance', 'best car insurance comparison'],
    publishedAt: '2026-05-09',
  },
];

export const getGuide = (slug: string) => guides.find(g => g.slug === slug);
